#! /usr/bin/expect

set timeout -1

spawn java ProductApp.java

set data {
    shortSleeve blue M 32
    shortSleeve red S 30
    shortSleeve yellow S 29
    shortPants magenta M 40
    shortPants cyan M 28
    shortPants black S 26
    booties baige L 33
    booties blue M 44
    booties red M 44
    booties pink L 44
}

foreach {type color size price} $data {
    expect "booties): "
    send "$type\r"

    expect "Color: "
    send "$color\r"

    expect "L): "
    send "$size\r"

    expect "Price: RM"
    send "$price\r"
}

expect eof
